-- Centralized scam blocklist shared across all installs.
-- Replaces the previously bundled assets/data/known_risks.json file.
--
-- Lookups: app fetches all rows on startup (cached locally for offline use).
-- Native CallScreeningService still reads its blocklist from a SharedPreferences
-- snapshot synced from this table.

create table if not exists public.known_risks (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('phone', 'bankAccount', 'url')),
  value text not null,
  normalized_value text not null,
  risk_level text not null check (risk_level in ('safe', 'suspicious', 'scam')),
  score int not null check (score between 0 and 100),
  summary text default '',
  reasons jsonb not null default '[]'::jsonb,
  psychological jsonb not null default '{}'::jsonb,
  linguistic_signals jsonb not null default '[]'::jsonb,
  cyber_signals jsonb not null default '[]'::jsonb,
  social_tactics jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (type, normalized_value)
);

create index if not exists known_risks_normalized_idx on public.known_risks (normalized_value);
create index if not exists known_risks_type_level_idx on public.known_risks (type, risk_level);

-- Updated-at trigger so client cache can detect changes.
create or replace function public.known_risks_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists known_risks_touch on public.known_risks;
create trigger known_risks_touch before update on public.known_risks
  for each row execute function public.known_risks_touch_updated_at();

-- Demo policy: anon can read everything, can also insert/update so the app
-- can submit community reports. Tighten to authenticated-only before go-prod.
alter table public.known_risks enable row level security;

drop policy if exists "anon read known_risks" on public.known_risks;
create policy "anon read known_risks" on public.known_risks
  for select to anon using (true);

drop policy if exists "anon insert known_risks" on public.known_risks;
create policy "anon insert known_risks" on public.known_risks
  for insert to anon with check (true);

drop policy if exists "anon update known_risks" on public.known_risks;
create policy "anon update known_risks" on public.known_risks
  for update to anon using (true) with check (true);

insert into public.known_risks
  (type, value, normalized_value, risk_level, score, summary, reasons, psychological, linguistic_signals, cyber_signals, social_tactics)
values
  ('phone', '0888888888', '0888888888', 'scam', 95, 'Số nằm trong danh sách lừa đảo đã được báo cáo nhiều lần.', '["Đã được báo cáo lừa đảo bởi nhiều nạn nhân.", "Mạo danh cơ quan công an để yêu cầu chuyển tiền.", "Sử dụng kịch bản đe doạ phong toả tài khoản."]'::jsonb, '{"urgency": 90, "fear": 95, "authority": 90, "greed": 10}'::jsonb, '["Sử dụng cụm từ kịch bản: ''tài khoản của bạn liên quan đường dây ma tuý''.", "Hối thúc liên tục bằng các từ khoá: ''ngay lập tức'', ''trong 5 phút''.", "Xưng hô không nhất quán (anh/chị/đồng chí) — dấu hiệu đọc kịch bản."]'::jsonb, '["Số nằm trong dải đầu thường được gắn cho các vụ giả danh cơ quan công an.", "Có thể giả lập caller ID — đối chiếu với tổng đài chính thức 113."]'::jsonb, '["Authority: giả danh công an / viện kiểm sát.", "Scarcity: tạo deadline ngắn để nạn nhân không kịp suy nghĩ.", "Commitment: ép cung cấp thông tin nhỏ trước rồi leo thang."]'::jsonb),
  ('phone', '0911222333', '0911222333', 'scam', 88, 'Số giả danh ngân hàng yêu cầu cập nhật thông tin tài khoản.', '["Mạo danh nhân viên ngân hàng.", "Yêu cầu cung cấp OTP, mã PIN hoặc mật khẩu.", "Hối thúc thực hiện giao dịch trong vài phút."]'::jsonb, '{"urgency": 85, "fear": 70, "authority": 80, "greed": 20}'::jsonb, '["Dùng từ chuyên ngành ngân hàng sai ngữ cảnh (''xác minh OTP cấp 2'').", "Câu mở đầu đặc trưng: ''Đây là tổng đài ABC Bank, gọi xác minh giao dịch''."]'::jsonb, '["Ngân hàng KHÔNG bao giờ hỏi OTP/PIN/mật khẩu qua điện thoại.", "Tổng đài chính thức của các ngân hàng VN bắt đầu bằng 1900 hoặc 1800."]'::jsonb, '["Authority: giả danh nhân viên ngân hàng.", "Urgency: ''tài khoản bị khoá trong 10 phút nếu không xác minh''."]'::jsonb),
  ('phone', '0369218921', '0369218921', 'scam', 93, 'Số bị tố cáo nhiều lần là lừa đảo qua điện thoại.', '["Có nhiều nạn nhân báo cáo bị lừa chuyển tiền.", "Tự xưng nhân viên giao hàng / shipper để dụ click link giả.", "Yêu cầu xác minh đơn hàng qua đường link lạ."]'::jsonb, '{"urgency": 85, "fear": 50, "authority": 70, "greed": 60}'::jsonb, '["Câu mẫu: ''Đơn hàng của bạn không giao được, vui lòng xác minh tại link…''.", "Sử dụng tên thương hiệu giao hàng (GHTK / SPX / J&T) để tăng độ tin cậy."]'::jsonb, '["Link xác minh không thuộc tên miền chính thức của hãng giao hàng.", "Trang đích thường lừa người dùng nhập OTP / số thẻ ngân hàng."]'::jsonb, '["Liking: tự xưng shipper, gọi tên thân thiện để hạ rào cản nghi ngờ.", "Commitment: xác nhận đơn hàng nhỏ trước rồi leo thang lên thanh toán."]'::jsonb),
  ('phone', '0388123456', '0388123456', 'suspicious', 55, 'Có một vài báo cáo nghi ngờ liên quan đến chào mời đầu tư.', '["Một số người dùng phản ánh nhận được lời mời đầu tư lãi cao bất thường.", "Chưa đủ bằng chứng để khẳng định lừa đảo nhưng cần cẩn trọng."]'::jsonb, '{"urgency": 40, "fear": 10, "authority": 30, "greed": 75}'::jsonb, '["Cụm từ marketing: ''lãi 30%/tháng'', ''bảo toàn vốn 100%'' — không có thật."]'::jsonb, '["Thường mời thêm Telegram / Zalo group, ngoài nền tảng có kiểm soát."]'::jsonb, '["Greed: hứa lợi nhuận cao bất thường.", "Social Proof: gửi screenshot ''người khác đã rút tiền thành công''."]'::jsonb),
  ('phone', '0838383838', '0838383838', 'scam', 92, 'Giả danh cán bộ Bộ Công an, đe doạ liên quan đến án ma tuý.', '["Tự xưng cán bộ điều tra Bộ Công an.", "Đọc đúng họ tên / CCCD nạn nhân để tăng độ tin cậy.", "Yêu cầu chuyển tiền vào ''tài khoản giám định'' để chứng minh trong sạch."]'::jsonb, '{"urgency": 92, "fear": 95, "authority": 95, "greed": 5}'::jsonb, '["Cụm từ: ''lệnh bắt khẩn cấp'', ''phong toả tài sản''.", "Doạ truy tố hình sự nếu không hợp tác."]'::jsonb, '["Công an thật KHÔNG làm việc qua điện thoại — đến trụ sở trực tiếp."]'::jsonb, '["Authority: giả danh công an cấp cao.", "Fear: đe doạ tù tội."]'::jsonb),
  ('phone', '0928374651', '0928374651', 'scam', 90, 'Giả danh Viện Kiểm sát triệu tập điều tra qua điện thoại.', '["Tự xưng kiểm sát viên.", "Cáo buộc nạn nhân rửa tiền.", "Đe doạ ra lệnh bắt nếu không hợp tác."]'::jsonb, '{"urgency": 90, "fear": 95, "authority": 95, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0782991122', '0782991122', 'scam', 91, 'Giả danh Toà án nhân dân thông báo có đơn kiện.', '["Tự xưng thư ký toà án.", "Cáo buộc nợ tín dụng / vi phạm hợp đồng.", "Đe doạ nếu không nộp ''phí xử lý''."]'::jsonb, '{"urgency": 85, "fear": 90, "authority": 90, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0563728190', '0563728190', 'scam', 89, 'Giả danh điều tra viên chuyển máy tới ''cấp trên'' tiếp tục đe doạ.', '["Sử dụng kịch bản nhiều cấp giả.", "Cố ý kéo dài cuộc gọi.", "Yêu cầu nạn nhân không kể với gia đình."]'::jsonb, '{"urgency": 88, "fear": 92, "authority": 88, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0942856173', '0942856173', 'scam', 90, 'Giả danh công an khu vực gọi ''xác minh hộ khẩu'' qua điện thoại.', '["Yêu cầu cung cấp số CCCD và mã định danh.", "Đe doạ phạt nếu không hợp tác.", "Xin link Zalo để gửi ''lệnh''."]'::jsonb, '{"urgency": 80, "fear": 85, "authority": 90, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0867432198', '0867432198', 'scam', 88, 'Giả danh nhân viên Vietcombank gọi xác minh giao dịch lạ.', '["Đọc đúng tên ngân hàng và 4 số cuối thẻ.", "Yêu cầu OTP để ''huỷ giao dịch lạ''.", "Hối thúc 5 phút."]'::jsonb, '{"urgency": 88, "fear": 75, "authority": 80, "greed": 10}'::jsonb, '[]'::jsonb, '["VCB chỉ liên hệ qua tổng đài 1900545486."]'::jsonb, '[]'::jsonb),
  ('phone', '0973516284', '0973516284', 'scam', 87, 'Giả danh BIDV cảnh báo tài khoản đăng nhập từ thiết bị lạ.', '["Yêu cầu cài app ''BIDV Smart'' giả từ link Zalo.", "App lừa thu thập SMS OTP."]'::jsonb, '{"urgency": 85, "fear": 70, "authority": 78, "greed": 8}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0335829471', '0335829471', 'scam', 89, 'Giả danh MB Bank thông báo nâng cấp thẻ ATM cần OTP.', '["Lý do giả: ''thẻ chip mới yêu cầu xác thực 2FA''.", "Yêu cầu chụp CCCD 2 mặt qua Zalo."]'::jsonb, '{"urgency": 80, "fear": 60, "authority": 80, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0568123094', '0568123094', 'scam', 86, 'Giả danh Techcombank yêu cầu mở app TCB từ link rút gọn.', '["Gửi link bit.ly redirect sang APK độc hại.", "App giả thu thập tin nhắn OTP và đăng nhập."]'::jsonb, '{"urgency": 78, "fear": 65, "authority": 75, "greed": 12}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0844672938', '0844672938', 'scam', 88, 'Giả danh VPBank thông báo nợ thẻ tín dụng quá hạn.', '["Tạo áp lực nợ xấu CIC.", "Yêu cầu chuyển tiền vào tài khoản trung gian."]'::jsonb, '{"urgency": 85, "fear": 80, "authority": 75, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0764382910', '0764382910', 'scam', 87, 'Giả danh ACB yêu cầu ''liên kết ví điện tử'' cần OTP.', '["Lừa khách hàng đồng ý liên kết với ví giả.", "Sau đó rút sạch số dư."]'::jsonb, '{"urgency": 82, "fear": 65, "authority": 78, "greed": 15}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0392845761', '0392845761', 'scam', 86, 'Giả danh Sacombank cảnh báo phát hiện đăng nhập từ Trung Quốc.', '["Đánh vào tâm lý lo sợ tài khoản bị hack.", "Yêu cầu OTP để ''reset bảo mật''."]'::jsonb, '{"urgency": 82, "fear": 80, "authority": 75, "greed": 8}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0987112233', '0987112233', 'scam', 89, 'Giả danh shipper Shopee yêu cầu xác minh đơn qua link.', '["Báo có đơn không giao được.", "Gửi link giả xác minh thu phí.", "Trang đích yêu cầu nhập thẻ ngân hàng."]'::jsonb, '{"urgency": 75, "fear": 35, "authority": 60, "greed": 50}'::jsonb, '[]'::jsonb, '["Domain xác minh KHÔNG thuộc shopee.vn."]'::jsonb, '[]'::jsonb),
  ('phone', '0356784291', '0356784291', 'scam', 88, 'Giả danh shipper J&T Express, đơn hàng không tồn tại.', '["Lừa người nhận trả ''phí giao hàng'' vào tài khoản cá nhân.", "Hối thúc đầu giờ làm việc."]'::jsonb, '{"urgency": 70, "fear": 30, "authority": 55, "greed": 55}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0773819246', '0773819246', 'scam', 87, 'Giả danh shipper GHTK gửi link ''xác minh người nhận''.', '["Trang xác minh giả mạo.", "Lừa nhập OTP ngân hàng."]'::jsonb, '{"urgency": 70, "fear": 25, "authority": 55, "greed": 50}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0915362847', '0915362847', 'scam', 86, 'Giả danh nhân viên SPX Express yêu cầu chuyển khoản nhận hàng COD giả.', '["Đơn không có thật nhưng đọc đúng địa chỉ nhà.", "Lừa chuyển trước nhận sau."]'::jsonb, '{"urgency": 70, "fear": 30, "authority": 50, "greed": 55}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0588193746', '0588193746', 'scam', 85, 'Giả danh GHN giao ''bưu phẩm quốc tế'' yêu cầu phí thuế.', '["Bịa quà từ nước ngoài.", "Phí thuế phải chuyển vào tài khoản cá nhân."]'::jsonb, '{"urgency": 65, "fear": 25, "authority": 50, "greed": 65}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0868294817', '0868294817', 'scam', 90, 'Tuyển CTV TikTok Shop nhận hoa hồng — thực chất nạp tiền nhiệm vụ.', '["Hứa thu nhập 500k–2tr/ngày.", "Yêu cầu nạp tiền nhiệm vụ ''để được đơn lớn hơn''.", "Mất tiền không thể rút."]'::jsonb, '{"urgency": 60, "fear": 10, "authority": 30, "greed": 95}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0942187364', '0942187364', 'scam', 88, 'Tuyển CTV like video YouTube / Telegram nhận tiền.', '["Trả 5–10k/like ''thử việc'' để gài bẫy.", "Sau đó yêu cầu nạp tiền ''nhiệm vụ VIP''.", "Block khi nạn nhân yêu cầu rút."]'::jsonb, '{"urgency": 50, "fear": 10, "authority": 25, "greed": 95}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0376918245', '0376918245', 'scam', 87, 'Lừa CTV bán hàng online tại nhà cần ''đặt cọc kho hàng''.', '["Yêu cầu chuyển khoản đặt cọc 1–3 triệu.", "Cam kết trả hoa hồng cao nhưng biến mất sau khi nhận tiền."]'::jsonb, '{"urgency": 55, "fear": 10, "authority": 30, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0795632841', '0795632841', 'scam', 88, 'Giả tuyển dụng Lazada / Tiki — bắt cài app làm nhiệm vụ giả.', '["App trên link không có trên Play Store.", "Hệ thống nhiệm vụ thưởng - nâng cấp - nạp tiền theo cấp."]'::jsonb, '{"urgency": 60, "fear": 10, "authority": 35, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0648372915', '0648372915', 'scam', 86, 'Lừa làm cộng tác viên Vinmart / WinMart đánh giá sản phẩm.', '["Trả hoa hồng bằng cách nạp tiền vào ví ảo.", "Rút tiền yêu cầu nạp thêm."]'::jsonb, '{"urgency": 50, "fear": 10, "authority": 30, "greed": 92}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0339817264', '0339817264', 'scam', 87, 'Giả danh cán bộ BHXH yêu cầu cập nhật thông tin định danh.', '["Yêu cầu chụp CCCD 2 mặt qua Zalo.", "Lấy thông tin để mở ví / vay tín dụng đen."]'::jsonb, '{"urgency": 70, "fear": 60, "authority": 80, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0973148265', '0973148265', 'scam', 86, 'Giả danh điện lực EVN doạ cắt điện vì ''nợ tiền''.', '["Yêu cầu chuyển tiền gấp vào tài khoản cá nhân.", "Doạ cắt điện trong 1 giờ."]'::jsonb, '{"urgency": 90, "fear": 70, "authority": 70, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0846281937', '0846281937', 'scam', 85, 'Giả danh nhân viên thuế yêu cầu nộp truy thu qua tài khoản lạ.', '["Cáo buộc kê khai sai thuế TNCN.", "Doạ phong toả tài khoản nếu không nộp ngay."]'::jsonb, '{"urgency": 80, "fear": 75, "authority": 80, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0556284917', '0556284917', 'scam', 84, 'Giả danh nhân viên y tế thông báo BHYT hết hạn.', '["Yêu cầu nộp phí ''gia hạn'' qua chuyển khoản.", "Đe doạ không được khám chữa bệnh."]'::jsonb, '{"urgency": 75, "fear": 65, "authority": 70, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0395847261', '0395847261', 'scam', 86, 'Giả danh cán bộ giáo dục báo con đang cấp cứu cần chuyển tiền viện phí.', '["Lừa phụ huynh đang đi làm.", "Tạo cảm xúc mạnh để nạn nhân không suy nghĩ."]'::jsonb, '{"urgency": 95, "fear": 95, "authority": 70, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0768294175', '0768294175', 'scam', 89, 'Mời đầu tư sàn forex ''lãi 30%/tháng'' — sàn ảo.', '["Tổ chức vào nhóm Telegram VIP.", "Có ''lệnh thắng'' giả để lấy lòng tin.", "Khi nạp lớn thì sập sàn."]'::jsonb, '{"urgency": 60, "fear": 15, "authority": 50, "greed": 95}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0918273645', '0918273645', 'scam', 88, 'Mời đầu tư crypto ''đào coin tự động'' - mô hình Ponzi.', '["Hứa lãi cố định hằng ngày.", "Đa cấp giới thiệu hoa hồng theo F1/F2/F3."]'::jsonb, '{"urgency": 55, "fear": 10, "authority": 40, "greed": 95}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0367192845', '0367192845', 'scam', 87, 'Chào mời ''cổ phiếu nội bộ'' chưa lên sàn từ công ty ma.', '["Thuyết phục là ''cơ hội ngàn năm có một''.", "Giấy tờ photoshop từ HoSE."]'::jsonb, '{"urgency": 65, "fear": 10, "authority": 60, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0526384791', '0526384791', 'scam', 85, 'Lừa nạn nhân vào group đầu tư chứng khoán Telegram, có ''thầy phím lệnh''.', '["Tăng vốn dần qua các khuyến nghị thắng giả.", "Khuyến nghị bán fake để pump-and-dump."]'::jsonb, '{"urgency": 50, "fear": 10, "authority": 65, "greed": 92}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0908172635', '0908172635', 'scam', 88, 'Tin nhắn / cuộc gọi báo trúng thưởng xe Honda SH / iPhone.', '["Yêu cầu nộp ''phí làm hồ sơ'' để nhận thưởng.", "Chuyển khoản nhiều lần với lý do thuế trước bạ."]'::jsonb, '{"urgency": 60, "fear": 10, "authority": 50, "greed": 92}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0856392841', '0856392841', 'scam', 86, 'Báo trúng thưởng từ chương trình ''tri ân khách hàng VIP'' của ngân hàng.', '["Bịa các chương trình không có thật.", "Yêu cầu cọc phí giải thưởng trước."]'::jsonb, '{"urgency": 55, "fear": 5, "authority": 55, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0397612845', '0397612845', 'scam', 84, 'Tự xưng quản trị viên Facebook báo trúng quà sinh nhật ZALO.', '["Yêu cầu OTP để ''kích hoạt giải thưởng''.", "Sử dụng OTP để chiếm Zalo."]'::jsonb, '{"urgency": 60, "fear": 5, "authority": 40, "greed": 85}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0367281946', '0367281946', 'scam', 85, 'Cho vay tiền online lãi suất ''ưu đãi'' không cần thế chấp.', '["Yêu cầu phí mở hồ sơ trước khi giải ngân.", "Sau khi nhận phí biến mất."]'::jsonb, '{"urgency": 50, "fear": 30, "authority": 40, "greed": 80}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0945718263', '0945718263', 'scam', 86, 'App vay nóng / vay nhanh không kiểm tra CIC — tín dụng đen.', '["Lãi suất ngầm 1000%/năm.", "Đòi nợ kiểu khủng bố cuộc gọi và Facebook gia đình."]'::jsonb, '{"urgency": 55, "fear": 60, "authority": 35, "greed": 70}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0782918374', '0782918374', 'scam', 84, 'Mời đảo nợ thẻ tín dụng — thực chất chiếm đoạt khoản đảo.', '["Hứa hỗ trợ trả nợ cũ rồi vay đảo lại.", "Lấy thông tin thẻ rồi rút sạch hạn mức."]'::jsonb, '{"urgency": 60, "fear": 50, "authority": 45, "greed": 65}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0938472615', '0938472615', 'scam', 89, 'Lừa hẹn hò online (love scam) — đối phương ''nước ngoài'' gửi quà.', '["Bạn ''người yêu'' tự xưng kỹ sư dầu khí / quân nhân.", "Sau đó báo có quà đắt tiền cần đóng phí hải quan.", "Đối phương thường tránh video call."]'::jsonb, '{"urgency": 55, "fear": 25, "authority": 40, "greed": 80}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0573829164', '0573829164', 'scam', 87, 'Giả người thân nhờ chuyển khoản gấp do ''mất ví''.', '["Hack Zalo / Facebook người quen rồi nhắn nhờ chuyển tiền.", "Số điện thoại lạ hoặc đầu số quốc tế."]'::jsonb, '{"urgency": 85, "fear": 60, "authority": 30, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0856372849', '0856372849', 'scam', 86, 'Bịa kịch bản ''chuyển khoản nhầm'' để gài bẫy hoàn tiền.', '["Chuyển vào tài khoản nạn nhân rồi yêu cầu hoàn lại.", "Sau đó báo công an về số tiền ''lừa đảo'' để gây áp lực."]'::jsonb, '{"urgency": 70, "fear": 70, "authority": 65, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0247361284', '0247361284', 'suspicious', 60, 'Số tổng đài lạ chào mời mua bảo hiểm nhân thọ.', '["Liên hệ liên tục mỗi ngày.", "Không cung cấp được mã đại lý / công văn ngân hàng."]'::jsonb, '{"urgency": 30, "fear": 10, "authority": 40, "greed": 50}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0289473625', '0289473625', 'suspicious', 55, 'Tổng đài giới thiệu thẻ tín dụng không yêu cầu chứng minh thu nhập.', '["Đề nghị quá dễ dãi so với ngân hàng thật.", "Yêu cầu chụp CCCD trước khi đối chiếu."]'::jsonb, '{"urgency": 25, "fear": 5, "authority": 40, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0246729384', '0246729384', 'suspicious', 50, 'Số liên hệ chào mời khoá học đầu tư chứng khoán ''miễn phí''.', '["Mục tiêu là kéo vào group bán khoá VIP và sàn ảo."]'::jsonb, '{"urgency": 25, "fear": 5, "authority": 35, "greed": 65}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0247193628', '0247193628', 'suspicious', 52, 'Telesales spam liên tục mời tham gia ''cộng đồng đầu tư bất động sản''.', '["Gọi nhiều lần / nhiều ngày dù bị từ chối.", "Tên dự án không tra được trên hệ thống Bộ Xây dựng."]'::jsonb, '{"urgency": 30, "fear": 5, "authority": 40, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0328374619', '0328374619', 'suspicious', 48, 'Số môi giới việc nhẹ lương cao tại Campuchia / Lào.', '["Tin tuyển ''nhân viên data entry'' lương 25–40 triệu.", "Có nhiều cảnh báo về buôn người tại các đặc khu."]'::jsonb, '{"urgency": 35, "fear": 15, "authority": 30, "greed": 80}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '0329837461', '0329837461', 'suspicious', 45, 'Số quảng cáo gói ''sim 4G data 1 năm 99k'' không rõ nguồn.', '["Yêu cầu chuyển khoản trước.", "Sim sau khi nhận có thể đã bị đăng ký bằng CCCD người khác."]'::jsonb, '{"urgency": 40, "fear": 5, "authority": 25, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '1900545486', '1900545486', 'safe', 5, 'Tổng đài chính thức của Vietcombank, đã xác minh.', '["Là số tổng đài công khai của ngân hàng Vietcombank.", "Không nằm trong danh sách báo cáo lừa đảo."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '1900636363', '1900636363', 'safe', 5, 'Tổng đài chăm sóc khách hàng VPBank, đã xác minh.', '["Là số tổng đài công khai của ngân hàng VPBank."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '19009247', '19009247', 'safe', 5, 'Tổng đài MB Bank chính thức.', '["Số hỗ trợ khách hàng được công bố trên mbbank.com.vn."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '19009448', '19009448', 'safe', 5, 'Tổng đài Techcombank chính thức.', '["Số hỗ trợ 24/7 công bố trên techcombank.com.vn."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '1900545413', '1900545413', 'safe', 5, 'Tổng đài BIDV SmartBanking.', '["Số hỗ trợ chính thức công bố tại bidv.com.vn."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '113', '113', 'safe', 0, 'Đường dây nóng Cảnh sát phản ứng nhanh (Bộ Công an).', '["Số khẩn cấp công khai toàn quốc."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('phone', '115', '115', 'safe', 0, 'Đường dây nóng cấp cứu y tế.', '["Số khẩn cấp công khai toàn quốc."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '19012345678', '19012345678', 'scam', 90, 'Tài khoản từng được dùng trong nhiều vụ lừa đảo chuyển khoản.', '["Có nhiều người báo cáo đã chuyển tiền và bị lừa.", "Tài khoản thường mở dưới tên người không liên quan (mua bán tài khoản)."]'::jsonb, '{"urgency": 80, "fear": 60, "authority": 50, "greed": 70}'::jsonb, '["Tên chủ tài khoản hiển thị thường khác hoàn toàn người liên hệ."]'::jsonb, '["Tài khoản trung gian (mule account) — có lịch sử nhận và chuyển ra liên tục.", "Mở dưới CMND/CCCD bị mua bán, khó truy ngược."]'::jsonb, '["Reciprocity: ''tặng quà / trúng thưởng'', yêu cầu chuyển phí trước.", "Authority: dùng logo ngân hàng / công văn giả để tăng độ tin cậy."]'::jsonb),
  ('bankAccount', '0987654321987', '0987654321987', 'suspicious', 50, 'Tài khoản nhận tiền từ các nguồn không rõ ràng, cần xác minh thêm.', '["Có lịch sử giao dịch bất thường về tần suất.", "Chưa có khiếu nại chính thức."]'::jsonb, '{"urgency": 35, "fear": 20, "authority": 20, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '0011001234567', '0011001234567', 'scam', 91, 'Tài khoản VCB mule, nhận tiền lừa đảo giả danh công an.', '["Tên chủ TK không khớp danh xưng người liên hệ.", "Tần suất nhận và chuyển ra trong vòng 5–10 phút."]'::jsonb, '{"urgency": 80, "fear": 75, "authority": 70, "greed": 30}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '12110002345678', '12110002345678', 'scam', 89, 'Tài khoản BIDV bị tố cáo lừa CTV TikTok Shop.', '["Chuyên nhận tiền ''nhiệm vụ'' rồi chặn liên lạc.", "Mở dưới CCCD đã được rao bán."]'::jsonb, '{"urgency": 60, "fear": 20, "authority": 35, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '9704161203748591', '9704161203748591', 'scam', 88, 'Tài khoản MB Bank dùng trong vụ giả shipper giao hàng quốc tế.', '["Nhiều nạn nhân chuyển 200–500k trước rồi mất liên lạc."]'::jsonb, '{"urgency": 65, "fear": 25, "authority": 50, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '11000123456', '11000123456', 'scam', 90, 'Tài khoản Techcombank dùng trong vụ giả danh viện kiểm sát.', '["Tài khoản ''phong toả giám định'' không tồn tại — chỉ là TK cá nhân.", "Liên kết với app cài qua link Zalo độc."]'::jsonb, '{"urgency": 90, "fear": 92, "authority": 90, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '00120036728', '00120036728', 'scam', 87, 'Tài khoản VPBank trung gian rút tiền sàn forex ảo.', '["Nạn nhân chuyển tiền ''nạp đầu tư'' không rút ra được.", "Sàn báo lỗi để giữ tiền."]'::jsonb, '{"urgency": 50, "fear": 15, "authority": 50, "greed": 92}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '9123456789', '9123456789', 'scam', 86, 'Tài khoản Sacombank dùng trong vụ vay tín dụng đen.', '["Yêu cầu phí mở hồ sơ chuyển vào TK cá nhân.", "Sau khi nhận phí biến mất."]'::jsonb, '{"urgency": 55, "fear": 30, "authority": 40, "greed": 75}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '1234567891234', '1234567891234', 'scam', 85, 'Tài khoản ACB dính 12 báo cáo trên trang chongluadao.vn.', '["Liên quan đến CTV bán hàng online.", "Bị chặn nhiều lần nhưng đổi tên chủ liên tục."]'::jsonb, '{"urgency": 50, "fear": 15, "authority": 40, "greed": 88}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '07021928374', '07021928374', 'scam', 84, 'Tài khoản TPBank giả danh nhân viên ngân hàng.', '["Đã có cảnh báo từ TPBank trên mạng xã hội chính thức."]'::jsonb, '{"urgency": 80, "fear": 65, "authority": 75, "greed": 15}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '150003049182', '150003049182', 'scam', 83, 'Tài khoản OCB liên quan vụ mạo danh nhân viên BHXH.', '["Thu phí ''gia hạn BHYT'' trái phép.", "BHXH KHÔNG bao giờ thu qua TK cá nhân."]'::jsonb, '{"urgency": 65, "fear": 60, "authority": 75, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '87654321098', '87654321098', 'scam', 88, 'Tài khoản Eximbank dùng trong vụ giả danh điện lực EVN.', '["Doạ cắt điện trong giờ.", "Yêu cầu chuyển khoản cá nhân thay vì code thanh toán EVN."]'::jsonb, '{"urgency": 90, "fear": 70, "authority": 70, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '8688100200300', '8688100200300', 'scam', 86, 'Tài khoản MSB sử dụng để rút tiền sau khi chiếm OTP.', '["Mở dưới CCCD bị mua bán trên Telegram.", "Lịch sử giao dịch toàn nhận-rút trong cùng phút."]'::jsonb, '{"urgency": 60, "fear": 50, "authority": 50, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '6868001234567', '6868001234567', 'scam', 85, 'Tài khoản Nam A Bank gắn với vụ love scam quà quốc tế.', '["Yêu cầu nạn nhân chuyển ''phí hải quan'' cho quà từ nước ngoài."]'::jsonb, '{"urgency": 60, "fear": 25, "authority": 45, "greed": 80}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '0307182937', '0307182937', 'scam', 84, 'Tài khoản SHB dùng trong vụ giả mạo đảo nợ thẻ tín dụng.', '["Chuyên rút sạch hạn mức thẻ ngay khi có OTP."]'::jsonb, '{"urgency": 65, "fear": 55, "authority": 50, "greed": 65}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '0210011223344', '0210011223344', 'scam', 87, 'Tài khoản VIB liên quan vụ giả tổng đài Lazada.', '["Lừa hoàn tiền đơn hàng cho khách.", "Lazada không hoàn tiền vào TK cá nhân không trùng đặt hàng."]'::jsonb, '{"urgency": 70, "fear": 30, "authority": 60, "greed": 50}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '1234556778899', '1234556778899', 'scam', 85, 'Tài khoản DongA Bank trung gian rút tiền lừa đảo Telegram.', '["Liên kết với group ''kiếm tiền online''.", "Tên TK thay đổi liên tục."]'::jsonb, '{"urgency": 55, "fear": 15, "authority": 40, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '2002003004005', '2002003004005', 'scam', 86, 'Tài khoản Agribank giả danh nhân viên bảo hiểm xã hội.', '["Yêu cầu nộp ''phí cập nhật BHYT'' qua TK cá nhân."]'::jsonb, '{"urgency": 70, "fear": 65, "authority": 75, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '555444333222', '555444333222', 'scam', 88, 'Tài khoản HDBank dùng trong vụ giả công an triệu tập điện thoại.', '["TK ''phong toả'' giả - thực chất TK cá nhân.", "Có cảnh báo từ Bộ Công an."]'::jsonb, '{"urgency": 92, "fear": 95, "authority": 95, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '1300210928374', '1300210928374', 'suspicious', 55, 'Tài khoản nghi vấn nhận tiền nhóm livestream bán hàng kém chất lượng.', '["Khách hàng phản ánh hàng nhái.", "Chưa có kết luận từ cơ quan chức năng."]'::jsonb, '{"urgency": 25, "fear": 10, "authority": 30, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '5687293048', '5687293048', 'suspicious', 50, 'TK nhận đặt cọc tour du lịch giá rẻ bất thường.', '["Một số khách hàng phản ánh không có chuyến."]'::jsonb, '{"urgency": 30, "fear": 15, "authority": 25, "greed": 65}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '39847261928', '39847261928', 'suspicious', 48, 'TK bán phụ kiện điện thoại trên TikTok Shop nghi gian lận đánh giá.', '["Đánh giá 5 sao bất thường tăng nhanh.", "Có khiếu nại đổi trả không xử lý."]'::jsonb, '{"urgency": 25, "fear": 5, "authority": 20, "greed": 55}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '7301928374650', '7301928374650', 'suspicious', 52, 'TK bán khoá học làm giàu online — chưa có kết luận lừa đảo.', '["Quảng cáo nhiều trên Facebook ads.", "Cam kết vô lý ''thu nhập 100tr/tháng''."]'::jsonb, '{"urgency": 30, "fear": 5, "authority": 35, "greed": 75}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '2901827364', '2901827364', 'suspicious', 45, 'TK nhận đặt cọc thuê nhà nguyên căn giá thấp bất thường.', '["Khách hàng bị chặn liên lạc sau khi cọc.", "Đăng tin trên các nhóm Facebook với nhiều ảnh khác nhau."]'::jsonb, '{"urgency": 35, "fear": 15, "authority": 25, "greed": 55}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '0011000345120', '0011000345120', 'safe', 5, 'TK ví dụ tổ chức từ thiện đã xác minh (demo).', '["Đã có giấy phép hoạt động xã hội.", "Sao kê công khai định kỳ."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('bankAccount', '111000222333', '111000222333', 'safe', 5, 'TK doanh nghiệp lớn đã được kiểm chứng (demo).', '["Đăng ký kinh doanh công khai.", "Đối chiếu được với MST."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'vietcombank-online.xyz', 'vietcombank-online.xyz', 'scam', 96, 'Trang web giả mạo Vietcombank nhằm đánh cắp thông tin đăng nhập.', '["Tên miền giả mạo Vietcombank, sai tên miền chính thức.", "Sử dụng đuôi .xyz không phải đuôi tổ chức tài chính.", "Form đăng nhập giống hệt trang thật để đánh cắp mật khẩu."]'::jsonb, '{"urgency": 70, "fear": 40, "authority": 90, "greed": 20}'::jsonb, '["Tiêu đề trang chứa từ khoá thương hiệu nhưng nội dung sao chép thiếu chỉn chu.", "Banner cảnh báo giả: ''Tài khoản của bạn cần cập nhật lại trong 24h''."]'::jsonb, '["Tên miền typo-squatting kèm chữ ''online'' — pattern phổ biến trong phishing.", "TLD .xyz không thuộc danh sách tên miền tổ chức tài chính tại VN.", "Trang thật là vietcombank.com.vn — đối chiếu chính tả từng chữ."]'::jsonb, '["Authority: nhái logo, footer Vietcombank.", "Scarcity: ''chỉ còn 24 giờ để xác minh''.", "Loss aversion: doạ khoá tài khoản nếu không thao tác."]'::jsonb),
  ('url', 'acb-bank.tk', 'acb-bank.tk', 'scam', 94, 'Trang phishing giả mạo ngân hàng ACB.', '["Tên miền .tk thường được dùng cho lừa đảo ngắn hạn.", "Mạo danh ngân hàng ACB chính thức (acb.com.vn).", "Yêu cầu nhập OTP và thông tin thẻ ngay trên trang."]'::jsonb, '{"urgency": 75, "fear": 60, "authority": 88, "greed": 15}'::jsonb, '["Sai chính tả ''Ngân Hàng ACB'' (viết hoa không nhất quán)."]'::jsonb, '["TLD .tk miễn phí, không yêu cầu xác minh — thường dùng phishing.", "Form yêu cầu OTP — ngân hàng thật không bao giờ thu OTP qua web ngoài."]'::jsonb, '["Authority: mạo danh ngân hàng ACB.", "Urgency: redirect tự động sau 10 giây nếu không thao tác."]'::jsonb),
  ('url', 'tuyendung-shopee-vn.com', 'tuyendung-shopee-vn.com', 'suspicious', 65, 'Trang nghi ngờ giả mạo tuyển dụng cộng tác viên Shopee.', '["Tên miền không thuộc shopee.vn chính thức.", "Yêu cầu nạp tiền để ''làm nhiệm vụ'' nhận hoa hồng – mô hình lừa đảo CTV phổ biến."]'::jsonb, '{"urgency": 60, "fear": 10, "authority": 45, "greed": 90}'::jsonb, '["Cụm từ: ''CTV nhận đơn ảo'', ''hoàn vốn sau 5 phút'', ''hoa hồng 15%/đơn''."]'::jsonb, '["Domain không thuộc shopee.vn — Shopee không tuyển CTV qua tên miền phụ ngẫu nhiên."]'::jsonb, '["Greed: hứa hoa hồng cao chỉ cần thao tác đơn giản.", "Commitment: bắt làm nhiệm vụ nhỏ trước, sau đó nâng số tiền nạp."]'::jsonb),
  ('url', 'vcb-online.top', 'vcb-online.top', 'scam', 95, 'Phishing Vietcombank — TLD .top thường dùng cho domain dùng 1 lần.', '["Tên miền không phải vietcombank.com.vn.", "Form đăng nhập giả mạo giao diện VCB Digibank."]'::jsonb, '{"urgency": 75, "fear": 50, "authority": 90, "greed": 15}'::jsonb, '[]'::jsonb, '["Trang thật: vietcombank.com.vn / vietcombank.com."]'::jsonb, '[]'::jsonb),
  ('url', 'vietcombank.com.online', 'vietcombank.com.online', 'scam', 94, 'Subdomain trick: vietcombank.com KHÔNG phải tên miền chính - phần chính là online.', '["Đây là subdomain của domain ''online'' nào đó.", "Người không kỹ sẽ tưởng là vietcombank.com."]'::jsonb, '{"urgency": 70, "fear": 50, "authority": 85, "greed": 10}'::jsonb, '[]'::jsonb, '["Tên miền chính của trang luôn là 2 phần cuối: ví dụ ở đây là ''com.online''."]'::jsonb, '[]'::jsonb),
  ('url', 'bidv-smart.icu', 'bidv-smart.icu', 'scam', 93, 'Phishing BIDV SmartBanking với TLD .icu rẻ tiền.', '["BIDV chính thức là bidv.com.vn.", ".icu không thuộc cấp domain ngân hàng."]'::jsonb, '{"urgency": 70, "fear": 55, "authority": 88, "greed": 12}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'mb-bank.cyou', 'mb-bank.cyou', 'scam', 92, 'Phishing MB Bank, TLD .cyou (read ''see you'') hay dùng cho phishing.', '["Trang gốc: mbbank.com.vn.", "Trang giả thu thập username + OTP."]'::jsonb, '{"urgency": 70, "fear": 50, "authority": 85, "greed": 15}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'techcombank-vip.top', 'techcombank-vip.top', 'scam', 91, 'Phishing Techcombank giả mạo chương trình ''tri ân khách hàng VIP''.', '["Yêu cầu đăng nhập + OTP để nhận quà.", "Domain không thuộc techcombank.com.vn."]'::jsonb, '{"urgency": 60, "fear": 30, "authority": 80, "greed": 75}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'vpbank-smart.tk', 'vpbank-smart.tk', 'scam', 92, 'Phishing VPBank, TLD .tk miễn phí dùng cho campaign phishing ngắn.', '["Domain rời rạc, không HTTPS hợp lệ.", "Form đăng nhập trộn cả số thẻ + CVV."]'::jsonb, '{"urgency": 75, "fear": 60, "authority": 85, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'agribank-online.cf', 'agribank-online.cf', 'scam', 91, 'Phishing Agribank cho khách nông thôn — domain TLD .cf miễn phí.', '["Agribank thật: agribank.com.vn.", "Trang giả tự đặt logo Agribank và ''cập nhật eKYC''."]'::jsonb, '{"urgency": 70, "fear": 60, "authority": 85, "greed": 8}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'sacombank-otp.xyz', 'sacombank-otp.xyz', 'scam', 92, 'Phishing Sacombank giả lập màn nhập OTP.', '["Tên miền có chữ ''otp'' - rất bất thường cho ngân hàng.", "Bắt nhập OTP để đánh cắp."]'::jsonb, '{"urgency": 80, "fear": 70, "authority": 80, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'tpbank-card.online', 'tpbank-card.online', 'scam', 90, 'Phishing TPBank yêu cầu cập nhật thông tin thẻ.', '["TPBank thật là tpb.vn / tpbank.com.vn.", "Trang giả thu thập số thẻ + CVV + ngày hết hạn."]'::jsonb, '{"urgency": 70, "fear": 50, "authority": 78, "greed": 10}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'ocb-bank.info', 'ocb-bank.info', 'scam', 88, 'Phishing OCB Omni với TLD .info.', '["Domain chính thức: ocb.com.vn.", "Trang phụ chiếm tài khoản ngân hàng."]'::jsonb, '{"urgency": 65, "fear": 45, "authority": 75, "greed": 12}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'shopee-mall-vn.com', 'shopee-mall-vn.com', 'scam', 89, 'Trang giả Shopee Mall, lừa đặt hàng giảm giá khủng.', '["Đặt hàng yêu cầu chuyển khoản trước 100%.", "Domain phụ — Shopee thật là shopee.vn."]'::jsonb, '{"urgency": 70, "fear": 10, "authority": 65, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'lazada-flashsale.top', 'lazada-flashsale.top', 'scam', 88, 'Trang flash sale Lazada giả tung mã giảm 90%.', '["Domain rất rẻ, không phải lazada.vn.", "Form thanh toán dẫn ra link Telegram bot."]'::jsonb, '{"urgency": 80, "fear": 5, "authority": 60, "greed": 95}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'tiki-ctv.com', 'tiki-ctv.com', 'scam', 87, 'Trang tuyển CTV bán hàng Tiki giả — bắt nạp ví theo nhiệm vụ.', '["Tiki không tuyển CTV qua các domain phụ ngẫu nhiên.", "Mô hình ví ảo điển hình của lừa đảo."]'::jsonb, '{"urgency": 60, "fear": 10, "authority": 50, "greed": 92}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'sendo-vn-promo.online', 'sendo-vn-promo.online', 'scam', 85, 'Trang khuyến mại Sendo giả mạo.', '["Sendo thật là sendo.vn.", "Yêu cầu CCCD + số thẻ tín dụng để ''xác minh nhận quà''."]'::jsonb, '{"urgency": 70, "fear": 10, "authority": 60, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'bhxh-online.vip', 'bhxh-online.vip', 'scam', 90, 'Trang giả Bảo hiểm Xã hội yêu cầu cập nhật thông tin định danh.', '["Cổng thật: baohiemxahoi.gov.vn / dichvucong.gov.vn.", "Domain TLD .vip không phải dịch vụ công."]'::jsonb, '{"urgency": 75, "fear": 65, "authority": 88, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'dichvucong-vn.top', 'dichvucong-vn.top', 'scam', 92, 'Trang giả Cổng dịch vụ công quốc gia.', '["Cổng thật: dichvucong.gov.vn.", "Trang giả thu thập CCCD, số điện thoại, mã định danh."]'::jsonb, '{"urgency": 75, "fear": 70, "authority": 92, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'thongtin-cccd.icu', 'thongtin-cccd.icu', 'scam', 91, 'Trang giả VNeID / cập nhật CCCD gắn chip.', '["VNeID thật là ứng dụng — KHÔNG cập nhật qua web bên ngoài.", "Trang yêu cầu chụp CCCD 2 mặt."]'::jsonb, '{"urgency": 70, "fear": 65, "authority": 92, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'vneid-update.tk', 'vneid-update.tk', 'scam', 91, 'Phishing giả VNeID với TLD .tk.', '["Bộ Công an không bao giờ yêu cầu cập nhật qua link Zalo / SMS.", "Trang yêu cầu OTP để ''xác thực''."]'::jsonb, '{"urgency": 75, "fear": 70, "authority": 92, "greed": 5}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'ghn-tracking.xyz', 'ghn-tracking.xyz', 'scam', 89, 'Trang giả tracking đơn hàng GHN — yêu cầu phí giao gấp.', '["GHN thật: ghn.vn.", "Trang giả bắt nhập số thẻ để ''thanh toán phí''."]'::jsonb, '{"urgency": 65, "fear": 25, "authority": 60, "greed": 50}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'ghtk-xacminh.cf', 'ghtk-xacminh.cf', 'scam', 88, 'Trang giả GHTK xác minh đơn hàng.', '["Domain TLD .cf miễn phí.", "Cố gắng đánh cắp OTP và thông tin thẻ."]'::jsonb, '{"urgency": 65, "fear": 25, "authority": 55, "greed": 55}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'spx-express-vn.online', 'spx-express-vn.online', 'scam', 87, 'Trang giả Shopee Express thông báo phí phụ.', '["SPX không thu phí qua web ngoài app Shopee.", "Trang giả yêu cầu chuyển khoản ngay."]'::jsonb, '{"urgency": 70, "fear": 30, "authority": 60, "greed": 50}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'jt-express-vn.top', 'jt-express-vn.top', 'scam', 86, 'Trang giả J&T Express yêu cầu xác nhận giao hàng quốc tế.', '["Trang thật: jtexpress.vn.", "Yêu cầu phí ''xử lý hải quan'' vào TK cá nhân."]'::jsonb, '{"urgency": 60, "fear": 20, "authority": 55, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'vietnamairlines-promo.icu', 'vietnamairlines-promo.icu', 'scam', 90, 'Trang giả Vietnam Airlines lừa đặt vé giá rẻ.', '["Trang thật: vietnamairlines.com.", "Trang giả yêu cầu chuyển khoản trước, không xuất e-ticket."]'::jsonb, '{"urgency": 70, "fear": 5, "authority": 75, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'vietjet-tickets-cheap.xyz', 'vietjet-tickets-cheap.xyz', 'scam', 88, 'Trang giả Vietjet bán vé khuyến mại 0đ.', '["Trang thật: vietjetair.com.", "Sau khi nhập thông tin thẻ, không có vé thực."]'::jsonb, '{"urgency": 75, "fear": 5, "authority": 70, "greed": 92}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'vnpost-tracuu.tk', 'vnpost-tracuu.tk', 'scam', 87, 'Trang giả VNPost tra cứu bưu phẩm và yêu cầu phí.', '["Trang thật: vnpost.vn.", "Bịa bưu phẩm quốc tế cần phí thuế."]'::jsonb, '{"urgency": 65, "fear": 30, "authority": 70, "greed": 60}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'kiemtien-online247.vip', 'kiemtien-online247.vip', 'suspicious', 60, 'Trang chào kiếm tiền online 24/7 không rõ mô hình.', '["Cam kết thu nhập cao bất thường.", "Đăng ký yêu cầu CCCD và số điện thoại."]'::jsonb, '{"urgency": 30, "fear": 5, "authority": 35, "greed": 88}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'dautu-coin-vn.top', 'dautu-coin-vn.top', 'suspicious', 58, 'Trang đầu tư coin chưa rõ giấy phép, đáng ngờ.', '["Việt Nam chưa cấp phép sàn coin tập trung.", "Cam kết lãi cố định/ngày — đặc trưng Ponzi."]'::jsonb, '{"urgency": 35, "fear": 10, "authority": 40, "greed": 90}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'review-shopee-thuong.online', 'review-shopee-thuong.online', 'suspicious', 55, 'Trang nhận làm nhiệm vụ review Shopee — chưa rõ có thực hay không.', '["Nhiều phản ánh sau khi nạp 1tr không rút được.", "Chưa có kết luận chính thức."]'::jsonb, '{"urgency": 30, "fear": 5, "authority": 30, "greed": 85}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'khoahoc-lamgiau.com', 'khoahoc-lamgiau.com', 'suspicious', 50, 'Trang bán khoá học làm giàu — quảng cáo phóng đại.', '["Lời hứa thu nhập 100tr/tháng vô lý.", "Người đứng tên không có chứng chỉ thật."]'::jsonb, '{"urgency": 25, "fear": 5, "authority": 35, "greed": 80}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'tour-rebate-vn.online', 'tour-rebate-vn.online', 'suspicious', 52, 'Trang chào tour du lịch giá thấp bất thường - cần xác minh.', '["Cọc 100% qua chuyển khoản cá nhân.", "Một vài khách hàng phản ánh không có chuyến."]'::jsonb, '{"urgency": 35, "fear": 10, "authority": 30, "greed": 70}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'vietcombank.com.vn', 'vietcombank.com.vn', 'safe', 3, 'Tên miền chính thức của ngân hàng Vietcombank.', '["Đây là tên miền chính thức được Vietcombank công bố."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'bidv.com.vn', 'bidv.com.vn', 'safe', 3, 'Tên miền chính thức của BIDV.', '["Domain chính thức công bố tại bidv.com.vn."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'mbbank.com.vn', 'mbbank.com.vn', 'safe', 3, 'Tên miền chính thức của MB Bank.', '["Domain chính thức công bố tại mbbank.com.vn."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'techcombank.com.vn', 'techcombank.com.vn', 'safe', 3, 'Tên miền chính thức của Techcombank.', '["Domain chính thức công bố tại techcombank.com.vn."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'shopee.vn', 'shopee.vn', 'safe', 3, 'Tên miền chính thức của Shopee Việt Nam.', '["Domain chính thức Shopee Việt Nam."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'dichvucong.gov.vn', 'dichvucong.gov.vn', 'safe', 0, 'Cổng dịch vụ công quốc gia chính thức.', '["TLD .gov.vn thuộc cơ quan nhà nước.", "Quản lý bởi VPCP."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb),
  ('url', 'baohiemxahoi.gov.vn', 'baohiemxahoi.gov.vn', 'safe', 0, 'Cổng Bảo hiểm Xã hội Việt Nam chính thức.', '["Domain .gov.vn của BHXH VN."]'::jsonb, '{"urgency": 0, "fear": 0, "authority": 0, "greed": 0}'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb)
on conflict (type, normalized_value) do update set
  value = excluded.value,
  risk_level = excluded.risk_level,
  score = excluded.score,
  summary = excluded.summary,
  reasons = excluded.reasons,
  psychological = excluded.psychological,
  linguistic_signals = excluded.linguistic_signals,
  cyber_signals = excluded.cyber_signals,
  social_tactics = excluded.social_tactics;
